services:
  db:
    image: postgres:latest
    container_name: chessbase_db_container
    restart: always
    environment:
      POSTGRES_USER: ${CHESSBASE_DB_USER}
      POSTGRES_PASSWORD: ${CHESSBASE_DB_PASSWORD}
      POSTGRES_DB: ${CHESSBASE_DB_NAME}
    ports:
      - "${CHESSBASE_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: