services:
  db:
    image: postgres:latest
    container_name: chessxiv_db_container
    restart: always
    environment:
      POSTGRES_USER: ${CHESSXIV_DB_USER}
      POSTGRES_PASSWORD: ${CHESSXIV_DB_PASSWORD}
      POSTGRES_DB: ${CHESSXIV_DB_NAME}
    ports:
      - "${CHESSXIV_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: