// <auto-generated />
using System;
using ChessXiv.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChessXiv.Infrastructure.Migrations
{
    [DbContext(typeof(ChessXivDbContext))]
    [Migration("20260328144123_OptimizePromotionHotPath")]
    partial class OptimizePromotionHotPath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChessXiv.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Black")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BlackElo")
                        .HasColumnType("integer");

                    b.Property<string>("BlackNormalizedFirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BlackNormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BlackNormalizedLastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BlackTitle")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ECO")
                        .HasColumnType("text");

                    b.Property<string>("Event")
                        .HasColumnType("text");

                    b.Property<string>("GameHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("boolean");

                    b.Property<int>("MoveCount")
                        .HasColumnType("integer");

                    b.Property<string>("Opening")
                        .HasColumnType("text");

                    b.Property<string>("Pgn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Round")
                        .HasColumnType("text");

                    b.Property<string>("Site")
                        .HasColumnType("text");

                    b.Property<string>("TimeControl")
                        .HasColumnType("text");

                    b.Property<string>("White")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WhiteElo")
                        .HasColumnType("integer");

                    b.Property<string>("WhiteNormalizedFirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WhiteNormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WhiteNormalizedLastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WhiteTitle")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameHash");

                    b.HasIndex("MoveCount");

                    b.HasIndex("BlackNormalizedFirstName", "BlackNormalizedLastName");

                    b.HasIndex("WhiteNormalizedFirstName", "WhiteNormalizedLastName");

                    b.HasIndex("Year", "Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Move", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlackClk")
                        .HasColumnType("text");

                    b.Property<double?>("BlackEval")
                        .HasColumnType("double precision");

                    b.Property<string>("BlackMove")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("MoveNumber")
                        .HasColumnType("integer");

                    b.Property<string>("WhiteClk")
                        .HasColumnType("text");

                    b.Property<double?>("WhiteEval")
                        .HasColumnType("double precision");

                    b.Property<string>("WhiteMove")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FenHash")
                        .HasColumnType("bigint");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastMove")
                        .HasColumnType("text");

                    b.Property<int>("PlyCount")
                        .HasColumnType("integer");

                    b.Property<char>("SideToMove")
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.HasIndex("FenHash");

                    b.HasIndex("GameId", "PlyCount");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.StagingGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Black")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BlackElo")
                        .HasColumnType("integer");

                    b.Property<string>("BlackNormalizedFirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BlackNormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BlackNormalizedLastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BlackTitle")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ECO")
                        .HasColumnType("text");

                    b.Property<string>("Event")
                        .HasColumnType("text");

                    b.Property<string>("GameHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MoveCount")
                        .HasColumnType("integer");

                    b.Property<string>("Opening")
                        .HasColumnType("text");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pgn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Round")
                        .HasColumnType("text");

                    b.Property<string>("Site")
                        .HasColumnType("text");

                    b.Property<string>("TimeControl")
                        .HasColumnType("text");

                    b.Property<string>("White")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WhiteElo")
                        .HasColumnType("integer");

                    b.Property<string>("WhiteNormalizedFirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WhiteNormalizedFullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("WhiteNormalizedLastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WhiteTitle")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "Black");

                    b.HasIndex("OwnerUserId", "CreatedAtUtc");

                    b.HasIndex("OwnerUserId", "GameHash");

                    b.HasIndex("OwnerUserId", "Id");

                    b.HasIndex("OwnerUserId", "White");

                    b.HasIndex("OwnerUserId", "BlackNormalizedFirstName", "BlackNormalizedLastName");

                    b.HasIndex("OwnerUserId", "WhiteNormalizedFirstName", "WhiteNormalizedLastName");

                    b.ToTable("StagingGames");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.StagingMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlackClk")
                        .HasColumnType("text");

                    b.Property<double?>("BlackEval")
                        .HasColumnType("double precision");

                    b.Property<string>("BlackMove")
                        .HasColumnType("text");

                    b.Property<int>("MoveNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("StagingGameId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhiteClk")
                        .HasColumnType("text");

                    b.Property<double?>("WhiteEval")
                        .HasColumnType("double precision");

                    b.Property<string>("WhiteMove")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StagingGameId");

                    b.ToTable("StagingMoves");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.StagingPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FenHash")
                        .HasColumnType("bigint");

                    b.Property<string>("LastMove")
                        .HasColumnType("text");

                    b.Property<int>("PlyCount")
                        .HasColumnType("integer");

                    b.Property<char>("SideToMove")
                        .HasColumnType("character(1)");

                    b.Property<Guid>("StagingGameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FenHash");

                    b.HasIndex("StagingGameId", "PlyCount");

                    b.ToTable("StagingPositions");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.UserDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic");

                    b.HasIndex("OwnerUserId", "Name")
                        .IsUnique();

                    b.ToTable("UserDatabases");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.UserDatabaseBookmark", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("UserDatabaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "UserDatabaseId");

                    b.HasIndex("UserDatabaseId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("UserDatabaseBookmarks");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.UserDatabaseGame", b =>
                {
                    b.Property<Guid>("UserDatabaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Event")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Round")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Site")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("UserDatabaseId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("UserDatabaseGames");
                });

            modelBuilder.Entity("ChessXiv.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserTier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Move", b =>
                {
                    b.HasOne("ChessXiv.Domain.Entities.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Position", b =>
                {
                    b.HasOne("ChessXiv.Domain.Entities.Game", "Game")
                        .WithMany("Positions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.StagingMove", b =>
                {
                    b.HasOne("ChessXiv.Domain.Entities.StagingGame", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("StagingGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.StagingPosition", b =>
                {
                    b.HasOne("ChessXiv.Domain.Entities.StagingGame", "Game")
                        .WithMany("Positions")
                        .HasForeignKey("StagingGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.UserDatabase", b =>
                {
                    b.HasOne("ChessXiv.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.UserDatabaseBookmark", b =>
                {
                    b.HasOne("ChessXiv.Domain.Entities.UserDatabase", "UserDatabase")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChessXiv.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDatabase");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.UserDatabaseGame", b =>
                {
                    b.HasOne("ChessXiv.Domain.Entities.Game", "Game")
                        .WithMany("UserDatabaseGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChessXiv.Domain.Entities.UserDatabase", "UserDatabase")
                        .WithMany("UserDatabaseGames")
                        .HasForeignKey("UserDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("UserDatabase");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ChessXiv.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ChessXiv.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChessXiv.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ChessXiv.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Game", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("Positions");

                    b.Navigation("UserDatabaseGames");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.StagingGame", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.UserDatabase", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("UserDatabaseGames");
                });
#pragma warning restore 612, 618
        }
    }
}
