// <auto-generated />
using System;
using ChessXiv.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChessXiv.Infrastructure.Migrations
{
    [DbContext(typeof(ChessXivDbContext))]
    [Migration("20260312102243_AddPlayerTable")]
    partial class AddPlayerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChessXiv.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Black")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BlackElo")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BlackPlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlackTitle")
                        .HasColumnType("text");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ECO")
                        .HasColumnType("text");

                    b.Property<string>("Event")
                        .HasColumnType("text");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("boolean");

                    b.Property<int>("MoveCount")
                        .HasColumnType("integer");

                    b.Property<string>("Opening")
                        .HasColumnType("text");

                    b.Property<string>("Pgn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Round")
                        .HasColumnType("text");

                    b.Property<string>("Site")
                        .HasColumnType("text");

                    b.Property<string>("TimeControl")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("White")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WhiteElo")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WhitePlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("WhiteTitle")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BlackPlayerId");

                    b.HasIndex("MoveCount");

                    b.HasIndex("WhitePlayerId");

                    b.HasIndex("Year", "Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Move", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlackClk")
                        .HasColumnType("text");

                    b.Property<double?>("BlackEval")
                        .HasColumnType("double precision");

                    b.Property<string>("BlackMove")
                        .HasColumnType("text");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<int>("MoveNumber")
                        .HasColumnType("integer");

                    b.Property<string>("WhiteClk")
                        .HasColumnType("text");

                    b.Property<double?>("WhiteEval")
                        .HasColumnType("double precision");

                    b.Property<string>("WhiteMove")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Moves");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedFirstName")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedLastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedFirstName");

                    b.HasIndex("NormalizedFullName")
                        .IsUnique();

                    b.HasIndex("NormalizedLastName");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Fen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FenHash")
                        .HasColumnType("bigint");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastMove")
                        .HasColumnType("text");

                    b.Property<int>("PlyCount")
                        .HasColumnType("integer");

                    b.Property<char>("SideToMove")
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.HasIndex("FenHash");

                    b.HasIndex("GameId", "PlyCount");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Game", b =>
                {
                    b.HasOne("ChessXiv.Domain.Entities.Player", "BlackPlayer")
                        .WithMany("GamesAsBlack")
                        .HasForeignKey("BlackPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChessXiv.Domain.Entities.Player", "WhitePlayer")
                        .WithMany("GamesAsWhite")
                        .HasForeignKey("WhitePlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BlackPlayer");

                    b.Navigation("WhitePlayer");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Move", b =>
                {
                    b.HasOne("ChessXiv.Domain.Entities.Game", "Game")
                        .WithMany("Moves")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Position", b =>
                {
                    b.HasOne("ChessXiv.Domain.Entities.Game", "Game")
                        .WithMany("Positions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Game", b =>
                {
                    b.Navigation("Moves");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("ChessXiv.Domain.Entities.Player", b =>
                {
                    b.Navigation("GamesAsBlack");

                    b.Navigation("GamesAsWhite");
                });
#pragma warning restore 612, 618
        }
    }
}
